---
- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Install git
      package:
        name:
          - git
          - bundler
          - ruby
        state: present
        update_cache: yes

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/{{ deploy_user }}/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/{{ deploy_user }}/reddit

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
